from io import BytesIO
from pkgutil import get_data
from gi.repository import GdkPixbuf
from signlangmtk.util import resource_location
import signlangmtk.difos.gui
from signlangmtk.__about__ import *


APP_ID = 'com.eigendomain.signlangmtk.difos'
APP_TITLE = 'Dif0s'

ABOUT_TITLE = 'Dif0s Sign Language Markup Tool'
DIFOS_VERSION = __version__
ABOUT_COMMENTS = ('The Sign Language Markup tool kit provides a set of'
                  + ' applications to model create'
                  + ' and search sign'
                  + ' language transcripts as described by Brenda Clark'
                  + ' at www.somewebsite.org.'
                  + ' (need citation). ' 
                  + ' If you use transcripts generated by this'
                  + ' tool kit you should'
                  + ' cite (blah) (see blah).')

CREDITS_SOFTWARE = ['Greg Clark <greg@eigendomain.com>']
CREDITS_CONCEPT = ['Brenda Clark <brendarc@hawaii.edu>']


def gui_resource(name):
    return resource_location(signlangmtk.difos.gui, name)


DIFOS_STYLE = gui_resource('dif0s_style.css')
ICON_FILE = gui_resource('dif0s.png')
ICON = GdkPixbuf.Pixbuf.new_from_file_at_size(ICON_FILE, 64, 64)

MAIN_WIN_UI = gui_resource('difos_main_window.ui')
MENU_UI = gui_resource('difos_menu.ui')

DEFAULT_WIN_SIZE_X = 300
DEFAULT_WIN_SIZE_Y = 300

EXPORT_SIZE_X = 300
EXPORT_SIZE_Y = 300
